// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: social.proto

package eu.trentorise.smartcampus.services.social.data.message;

public final class Social {
  private Social() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NewsListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .eu.trentorise.smartcampus.services.social.data.message.News news = 1;
    java.util.List<eu.trentorise.smartcampus.services.social.data.message.Social.News> 
        getNewsList();
    eu.trentorise.smartcampus.services.social.data.message.Social.News getNews(int index);
    int getNewsCount();
    java.util.List<? extends eu.trentorise.smartcampus.services.social.data.message.Social.NewsOrBuilder> 
        getNewsOrBuilderList();
    eu.trentorise.smartcampus.services.social.data.message.Social.NewsOrBuilder getNewsOrBuilder(
        int index);
    
    // required int64 socialId = 2;
    boolean hasSocialId();
    long getSocialId();
  }
  public static final class NewsList extends
      com.google.protobuf.GeneratedMessage
      implements NewsListOrBuilder {
    // Use NewsList.newBuilder() to construct.
    private NewsList(Builder builder) {
      super(builder);
    }
    private NewsList(boolean noInit) {}
    
    private static final NewsList defaultInstance;
    public static NewsList getDefaultInstance() {
      return defaultInstance;
    }
    
    public NewsList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.services.social.data.message.Social.internal_static_eu_trentorise_smartcampus_services_social_data_message_NewsList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.services.social.data.message.Social.internal_static_eu_trentorise_smartcampus_services_social_data_message_NewsList_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated .eu.trentorise.smartcampus.services.social.data.message.News news = 1;
    public static final int NEWS_FIELD_NUMBER = 1;
    private java.util.List<eu.trentorise.smartcampus.services.social.data.message.Social.News> news_;
    public java.util.List<eu.trentorise.smartcampus.services.social.data.message.Social.News> getNewsList() {
      return news_;
    }
    public java.util.List<? extends eu.trentorise.smartcampus.services.social.data.message.Social.NewsOrBuilder> 
        getNewsOrBuilderList() {
      return news_;
    }
    public int getNewsCount() {
      return news_.size();
    }
    public eu.trentorise.smartcampus.services.social.data.message.Social.News getNews(int index) {
      return news_.get(index);
    }
    public eu.trentorise.smartcampus.services.social.data.message.Social.NewsOrBuilder getNewsOrBuilder(
        int index) {
      return news_.get(index);
    }
    
    // required int64 socialId = 2;
    public static final int SOCIALID_FIELD_NUMBER = 2;
    private long socialId_;
    public boolean hasSocialId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getSocialId() {
      return socialId_;
    }
    
    private void initFields() {
      news_ = java.util.Collections.emptyList();
      socialId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSocialId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getNewsCount(); i++) {
        if (!getNews(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < news_.size(); i++) {
        output.writeMessage(1, news_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(2, socialId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < news_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, news_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, socialId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.services.social.data.message.Social.NewsList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.NewsList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.NewsList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.NewsList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.NewsList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.NewsList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.NewsList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.NewsList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.NewsList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.NewsList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.services.social.data.message.Social.NewsList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.services.social.data.message.Social.NewsListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.services.social.data.message.Social.internal_static_eu_trentorise_smartcampus_services_social_data_message_NewsList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.services.social.data.message.Social.internal_static_eu_trentorise_smartcampus_services_social_data_message_NewsList_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.services.social.data.message.Social.NewsList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNewsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (newsBuilder_ == null) {
          news_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          newsBuilder_.clear();
        }
        socialId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.services.social.data.message.Social.NewsList.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.services.social.data.message.Social.NewsList getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.services.social.data.message.Social.NewsList.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.services.social.data.message.Social.NewsList build() {
        eu.trentorise.smartcampus.services.social.data.message.Social.NewsList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.services.social.data.message.Social.NewsList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.services.social.data.message.Social.NewsList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.services.social.data.message.Social.NewsList buildPartial() {
        eu.trentorise.smartcampus.services.social.data.message.Social.NewsList result = new eu.trentorise.smartcampus.services.social.data.message.Social.NewsList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (newsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            news_ = java.util.Collections.unmodifiableList(news_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.news_ = news_;
        } else {
          result.news_ = newsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.socialId_ = socialId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.services.social.data.message.Social.NewsList) {
          return mergeFrom((eu.trentorise.smartcampus.services.social.data.message.Social.NewsList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.services.social.data.message.Social.NewsList other) {
        if (other == eu.trentorise.smartcampus.services.social.data.message.Social.NewsList.getDefaultInstance()) return this;
        if (newsBuilder_ == null) {
          if (!other.news_.isEmpty()) {
            if (news_.isEmpty()) {
              news_ = other.news_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNewsIsMutable();
              news_.addAll(other.news_);
            }
            onChanged();
          }
        } else {
          if (!other.news_.isEmpty()) {
            if (newsBuilder_.isEmpty()) {
              newsBuilder_.dispose();
              newsBuilder_ = null;
              news_ = other.news_;
              bitField0_ = (bitField0_ & ~0x00000001);
              newsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNewsFieldBuilder() : null;
            } else {
              newsBuilder_.addAllMessages(other.news_);
            }
          }
        }
        if (other.hasSocialId()) {
          setSocialId(other.getSocialId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSocialId()) {
          
          return false;
        }
        for (int i = 0; i < getNewsCount(); i++) {
          if (!getNews(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              eu.trentorise.smartcampus.services.social.data.message.Social.News.Builder subBuilder = eu.trentorise.smartcampus.services.social.data.message.Social.News.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNews(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              socialId_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .eu.trentorise.smartcampus.services.social.data.message.News news = 1;
      private java.util.List<eu.trentorise.smartcampus.services.social.data.message.Social.News> news_ =
        java.util.Collections.emptyList();
      private void ensureNewsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          news_ = new java.util.ArrayList<eu.trentorise.smartcampus.services.social.data.message.Social.News>(news_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.services.social.data.message.Social.News, eu.trentorise.smartcampus.services.social.data.message.Social.News.Builder, eu.trentorise.smartcampus.services.social.data.message.Social.NewsOrBuilder> newsBuilder_;
      
      public java.util.List<eu.trentorise.smartcampus.services.social.data.message.Social.News> getNewsList() {
        if (newsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(news_);
        } else {
          return newsBuilder_.getMessageList();
        }
      }
      public int getNewsCount() {
        if (newsBuilder_ == null) {
          return news_.size();
        } else {
          return newsBuilder_.getCount();
        }
      }
      public eu.trentorise.smartcampus.services.social.data.message.Social.News getNews(int index) {
        if (newsBuilder_ == null) {
          return news_.get(index);
        } else {
          return newsBuilder_.getMessage(index);
        }
      }
      public Builder setNews(
          int index, eu.trentorise.smartcampus.services.social.data.message.Social.News value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.set(index, value);
          onChanged();
        } else {
          newsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNews(
          int index, eu.trentorise.smartcampus.services.social.data.message.Social.News.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.set(index, builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNews(eu.trentorise.smartcampus.services.social.data.message.Social.News value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.add(value);
          onChanged();
        } else {
          newsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNews(
          int index, eu.trentorise.smartcampus.services.social.data.message.Social.News value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.add(index, value);
          onChanged();
        } else {
          newsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNews(
          eu.trentorise.smartcampus.services.social.data.message.Social.News.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.add(builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNews(
          int index, eu.trentorise.smartcampus.services.social.data.message.Social.News.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.add(index, builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNews(
          java.lang.Iterable<? extends eu.trentorise.smartcampus.services.social.data.message.Social.News> values) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          super.addAll(values, news_);
          onChanged();
        } else {
          newsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNews() {
        if (newsBuilder_ == null) {
          news_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          newsBuilder_.clear();
        }
        return this;
      }
      public Builder removeNews(int index) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.remove(index);
          onChanged();
        } else {
          newsBuilder_.remove(index);
        }
        return this;
      }
      public eu.trentorise.smartcampus.services.social.data.message.Social.News.Builder getNewsBuilder(
          int index) {
        return getNewsFieldBuilder().getBuilder(index);
      }
      public eu.trentorise.smartcampus.services.social.data.message.Social.NewsOrBuilder getNewsOrBuilder(
          int index) {
        if (newsBuilder_ == null) {
          return news_.get(index);  } else {
          return newsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends eu.trentorise.smartcampus.services.social.data.message.Social.NewsOrBuilder> 
           getNewsOrBuilderList() {
        if (newsBuilder_ != null) {
          return newsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(news_);
        }
      }
      public eu.trentorise.smartcampus.services.social.data.message.Social.News.Builder addNewsBuilder() {
        return getNewsFieldBuilder().addBuilder(
            eu.trentorise.smartcampus.services.social.data.message.Social.News.getDefaultInstance());
      }
      public eu.trentorise.smartcampus.services.social.data.message.Social.News.Builder addNewsBuilder(
          int index) {
        return getNewsFieldBuilder().addBuilder(
            index, eu.trentorise.smartcampus.services.social.data.message.Social.News.getDefaultInstance());
      }
      public java.util.List<eu.trentorise.smartcampus.services.social.data.message.Social.News.Builder> 
           getNewsBuilderList() {
        return getNewsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.services.social.data.message.Social.News, eu.trentorise.smartcampus.services.social.data.message.Social.News.Builder, eu.trentorise.smartcampus.services.social.data.message.Social.NewsOrBuilder> 
          getNewsFieldBuilder() {
        if (newsBuilder_ == null) {
          newsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.trentorise.smartcampus.services.social.data.message.Social.News, eu.trentorise.smartcampus.services.social.data.message.Social.News.Builder, eu.trentorise.smartcampus.services.social.data.message.Social.NewsOrBuilder>(
                  news_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          news_ = null;
        }
        return newsBuilder_;
      }
      
      // required int64 socialId = 2;
      private long socialId_ ;
      public boolean hasSocialId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getSocialId() {
        return socialId_;
      }
      public Builder setSocialId(long value) {
        bitField0_ |= 0x00000002;
        socialId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSocialId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        socialId_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.services.social.data.message.NewsList)
    }
    
    static {
      defaultInstance = new NewsList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.services.social.data.message.NewsList)
  }
  
  public interface NewsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 id = 1;
    boolean hasId();
    long getId();
    
    // required int64 creationTimestamp = 2;
    boolean hasCreationTimestamp();
    long getCreationTimestamp();
    
    // required int64 entityId = 3;
    boolean hasEntityId();
    long getEntityId();
    
    // required string entityType = 4;
    boolean hasEntityType();
    String getEntityType();
    
    // required int64 topicId = 5;
    boolean hasTopicId();
    long getTopicId();
    
    // required string topicName = 6;
    boolean hasTopicName();
    String getTopicName();
    
    // required bool update = 7;
    boolean hasUpdate();
    boolean getUpdate();
    
    // optional string title = 8;
    boolean hasTitle();
    String getTitle();
    
    // optional int64 providerId = 9;
    boolean hasProviderId();
    long getProviderId();
    
    // optional .eu.trentorise.smartcampus.services.social.data.message.SEntity related = 10;
    boolean hasRelated();
    eu.trentorise.smartcampus.services.social.data.message.Social.SEntity getRelated();
    eu.trentorise.smartcampus.services.social.data.message.Social.SEntityOrBuilder getRelatedOrBuilder();
  }
  public static final class News extends
      com.google.protobuf.GeneratedMessage
      implements NewsOrBuilder {
    // Use News.newBuilder() to construct.
    private News(Builder builder) {
      super(builder);
    }
    private News(boolean noInit) {}
    
    private static final News defaultInstance;
    public static News getDefaultInstance() {
      return defaultInstance;
    }
    
    public News getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.services.social.data.message.Social.internal_static_eu_trentorise_smartcampus_services_social_data_message_News_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.services.social.data.message.Social.internal_static_eu_trentorise_smartcampus_services_social_data_message_News_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // required int64 creationTimestamp = 2;
    public static final int CREATIONTIMESTAMP_FIELD_NUMBER = 2;
    private long creationTimestamp_;
    public boolean hasCreationTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getCreationTimestamp() {
      return creationTimestamp_;
    }
    
    // required int64 entityId = 3;
    public static final int ENTITYID_FIELD_NUMBER = 3;
    private long entityId_;
    public boolean hasEntityId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getEntityId() {
      return entityId_;
    }
    
    // required string entityType = 4;
    public static final int ENTITYTYPE_FIELD_NUMBER = 4;
    private java.lang.Object entityType_;
    public boolean hasEntityType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getEntityType() {
      java.lang.Object ref = entityType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          entityType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEntityTypeBytes() {
      java.lang.Object ref = entityType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        entityType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 topicId = 5;
    public static final int TOPICID_FIELD_NUMBER = 5;
    private long topicId_;
    public boolean hasTopicId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getTopicId() {
      return topicId_;
    }
    
    // required string topicName = 6;
    public static final int TOPICNAME_FIELD_NUMBER = 6;
    private java.lang.Object topicName_;
    public boolean hasTopicName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getTopicName() {
      java.lang.Object ref = topicName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          topicName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTopicNameBytes() {
      java.lang.Object ref = topicName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        topicName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bool update = 7;
    public static final int UPDATE_FIELD_NUMBER = 7;
    private boolean update_;
    public boolean hasUpdate() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public boolean getUpdate() {
      return update_;
    }
    
    // optional string title = 8;
    public static final int TITLE_FIELD_NUMBER = 8;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 providerId = 9;
    public static final int PROVIDERID_FIELD_NUMBER = 9;
    private long providerId_;
    public boolean hasProviderId() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public long getProviderId() {
      return providerId_;
    }
    
    // optional .eu.trentorise.smartcampus.services.social.data.message.SEntity related = 10;
    public static final int RELATED_FIELD_NUMBER = 10;
    private eu.trentorise.smartcampus.services.social.data.message.Social.SEntity related_;
    public boolean hasRelated() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public eu.trentorise.smartcampus.services.social.data.message.Social.SEntity getRelated() {
      return related_;
    }
    public eu.trentorise.smartcampus.services.social.data.message.Social.SEntityOrBuilder getRelatedOrBuilder() {
      return related_;
    }
    
    private void initFields() {
      id_ = 0L;
      creationTimestamp_ = 0L;
      entityId_ = 0L;
      entityType_ = "";
      topicId_ = 0L;
      topicName_ = "";
      update_ = false;
      title_ = "";
      providerId_ = 0L;
      related_ = eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreationTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEntityId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEntityType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTopicId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTopicName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUpdate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRelated()) {
        if (!getRelated().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, creationTimestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, entityId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getEntityTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, topicId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTopicNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, update_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getTitleBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, providerId_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeMessage(10, related_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, creationTimestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, entityId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getEntityTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, topicId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTopicNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, update_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getTitleBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, providerId_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, related_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.services.social.data.message.Social.News parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.News parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.News parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.News parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.News parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.News parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.News parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.News parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.News parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.News parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.services.social.data.message.Social.News prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.services.social.data.message.Social.NewsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.services.social.data.message.Social.internal_static_eu_trentorise_smartcampus_services_social_data_message_News_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.services.social.data.message.Social.internal_static_eu_trentorise_smartcampus_services_social_data_message_News_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.services.social.data.message.Social.News.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRelatedFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        creationTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        entityId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        entityType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        topicId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        topicName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        update_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        providerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        if (relatedBuilder_ == null) {
          related_ = eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.getDefaultInstance();
        } else {
          relatedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.services.social.data.message.Social.News.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.services.social.data.message.Social.News getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.services.social.data.message.Social.News.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.services.social.data.message.Social.News build() {
        eu.trentorise.smartcampus.services.social.data.message.Social.News result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.services.social.data.message.Social.News buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.services.social.data.message.Social.News result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.services.social.data.message.Social.News buildPartial() {
        eu.trentorise.smartcampus.services.social.data.message.Social.News result = new eu.trentorise.smartcampus.services.social.data.message.Social.News(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.creationTimestamp_ = creationTimestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.entityId_ = entityId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.entityType_ = entityType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.topicId_ = topicId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.topicName_ = topicName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.update_ = update_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.providerId_ = providerId_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        if (relatedBuilder_ == null) {
          result.related_ = related_;
        } else {
          result.related_ = relatedBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.services.social.data.message.Social.News) {
          return mergeFrom((eu.trentorise.smartcampus.services.social.data.message.Social.News)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.services.social.data.message.Social.News other) {
        if (other == eu.trentorise.smartcampus.services.social.data.message.Social.News.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCreationTimestamp()) {
          setCreationTimestamp(other.getCreationTimestamp());
        }
        if (other.hasEntityId()) {
          setEntityId(other.getEntityId());
        }
        if (other.hasEntityType()) {
          setEntityType(other.getEntityType());
        }
        if (other.hasTopicId()) {
          setTopicId(other.getTopicId());
        }
        if (other.hasTopicName()) {
          setTopicName(other.getTopicName());
        }
        if (other.hasUpdate()) {
          setUpdate(other.getUpdate());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasProviderId()) {
          setProviderId(other.getProviderId());
        }
        if (other.hasRelated()) {
          mergeRelated(other.getRelated());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasCreationTimestamp()) {
          
          return false;
        }
        if (!hasEntityId()) {
          
          return false;
        }
        if (!hasEntityType()) {
          
          return false;
        }
        if (!hasTopicId()) {
          
          return false;
        }
        if (!hasTopicName()) {
          
          return false;
        }
        if (!hasUpdate()) {
          
          return false;
        }
        if (hasRelated()) {
          if (!getRelated().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              creationTimestamp_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              entityId_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              entityType_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              topicId_ = input.readInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              topicName_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              update_ = input.readBool();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              title_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              providerId_ = input.readInt64();
              break;
            }
            case 82: {
              eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.Builder subBuilder = eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.newBuilder();
              if (hasRelated()) {
                subBuilder.mergeFrom(getRelated());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRelated(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 creationTimestamp = 2;
      private long creationTimestamp_ ;
      public boolean hasCreationTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getCreationTimestamp() {
        return creationTimestamp_;
      }
      public Builder setCreationTimestamp(long value) {
        bitField0_ |= 0x00000002;
        creationTimestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreationTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        creationTimestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 entityId = 3;
      private long entityId_ ;
      public boolean hasEntityId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getEntityId() {
        return entityId_;
      }
      public Builder setEntityId(long value) {
        bitField0_ |= 0x00000004;
        entityId_ = value;
        onChanged();
        return this;
      }
      public Builder clearEntityId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        entityId_ = 0L;
        onChanged();
        return this;
      }
      
      // required string entityType = 4;
      private java.lang.Object entityType_ = "";
      public boolean hasEntityType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getEntityType() {
        java.lang.Object ref = entityType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          entityType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEntityType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        entityType_ = value;
        onChanged();
        return this;
      }
      public Builder clearEntityType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        entityType_ = getDefaultInstance().getEntityType();
        onChanged();
        return this;
      }
      void setEntityType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        entityType_ = value;
        onChanged();
      }
      
      // required int64 topicId = 5;
      private long topicId_ ;
      public boolean hasTopicId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getTopicId() {
        return topicId_;
      }
      public Builder setTopicId(long value) {
        bitField0_ |= 0x00000010;
        topicId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTopicId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        topicId_ = 0L;
        onChanged();
        return this;
      }
      
      // required string topicName = 6;
      private java.lang.Object topicName_ = "";
      public boolean hasTopicName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getTopicName() {
        java.lang.Object ref = topicName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          topicName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTopicName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        topicName_ = value;
        onChanged();
        return this;
      }
      public Builder clearTopicName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        topicName_ = getDefaultInstance().getTopicName();
        onChanged();
        return this;
      }
      void setTopicName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        topicName_ = value;
        onChanged();
      }
      
      // required bool update = 7;
      private boolean update_ ;
      public boolean hasUpdate() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public boolean getUpdate() {
        return update_;
      }
      public Builder setUpdate(boolean value) {
        bitField0_ |= 0x00000040;
        update_ = value;
        onChanged();
        return this;
      }
      public Builder clearUpdate() {
        bitField0_ = (bitField0_ & ~0x00000040);
        update_ = false;
        onChanged();
        return this;
      }
      
      // optional string title = 8;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000080);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        title_ = value;
        onChanged();
      }
      
      // optional int64 providerId = 9;
      private long providerId_ ;
      public boolean hasProviderId() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public long getProviderId() {
        return providerId_;
      }
      public Builder setProviderId(long value) {
        bitField0_ |= 0x00000100;
        providerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearProviderId() {
        bitField0_ = (bitField0_ & ~0x00000100);
        providerId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .eu.trentorise.smartcampus.services.social.data.message.SEntity related = 10;
      private eu.trentorise.smartcampus.services.social.data.message.Social.SEntity related_ = eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          eu.trentorise.smartcampus.services.social.data.message.Social.SEntity, eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.Builder, eu.trentorise.smartcampus.services.social.data.message.Social.SEntityOrBuilder> relatedBuilder_;
      public boolean hasRelated() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public eu.trentorise.smartcampus.services.social.data.message.Social.SEntity getRelated() {
        if (relatedBuilder_ == null) {
          return related_;
        } else {
          return relatedBuilder_.getMessage();
        }
      }
      public Builder setRelated(eu.trentorise.smartcampus.services.social.data.message.Social.SEntity value) {
        if (relatedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          related_ = value;
          onChanged();
        } else {
          relatedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      public Builder setRelated(
          eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.Builder builderForValue) {
        if (relatedBuilder_ == null) {
          related_ = builderForValue.build();
          onChanged();
        } else {
          relatedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      public Builder mergeRelated(eu.trentorise.smartcampus.services.social.data.message.Social.SEntity value) {
        if (relatedBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200) &&
              related_ != eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.getDefaultInstance()) {
            related_ =
              eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.newBuilder(related_).mergeFrom(value).buildPartial();
          } else {
            related_ = value;
          }
          onChanged();
        } else {
          relatedBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      public Builder clearRelated() {
        if (relatedBuilder_ == null) {
          related_ = eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.getDefaultInstance();
          onChanged();
        } else {
          relatedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      public eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.Builder getRelatedBuilder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return getRelatedFieldBuilder().getBuilder();
      }
      public eu.trentorise.smartcampus.services.social.data.message.Social.SEntityOrBuilder getRelatedOrBuilder() {
        if (relatedBuilder_ != null) {
          return relatedBuilder_.getMessageOrBuilder();
        } else {
          return related_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          eu.trentorise.smartcampus.services.social.data.message.Social.SEntity, eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.Builder, eu.trentorise.smartcampus.services.social.data.message.Social.SEntityOrBuilder> 
          getRelatedFieldBuilder() {
        if (relatedBuilder_ == null) {
          relatedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              eu.trentorise.smartcampus.services.social.data.message.Social.SEntity, eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.Builder, eu.trentorise.smartcampus.services.social.data.message.Social.SEntityOrBuilder>(
                  related_,
                  getParentForChildren(),
                  isClean());
          related_ = null;
        }
        return relatedBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.services.social.data.message.News)
    }
    
    static {
      defaultInstance = new News(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.services.social.data.message.News)
  }
  
  public interface SEntityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 id = 1;
    boolean hasId();
    long getId();
    
    // optional string title = 2;
    boolean hasTitle();
    String getTitle();
    
    // required string entityType = 3;
    boolean hasEntityType();
    String getEntityType();
  }
  public static final class SEntity extends
      com.google.protobuf.GeneratedMessage
      implements SEntityOrBuilder {
    // Use SEntity.newBuilder() to construct.
    private SEntity(Builder builder) {
      super(builder);
    }
    private SEntity(boolean noInit) {}
    
    private static final SEntity defaultInstance;
    public static SEntity getDefaultInstance() {
      return defaultInstance;
    }
    
    public SEntity getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.services.social.data.message.Social.internal_static_eu_trentorise_smartcampus_services_social_data_message_SEntity_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.services.social.data.message.Social.internal_static_eu_trentorise_smartcampus_services_social_data_message_SEntity_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string entityType = 3;
    public static final int ENTITYTYPE_FIELD_NUMBER = 3;
    private java.lang.Object entityType_;
    public boolean hasEntityType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getEntityType() {
      java.lang.Object ref = entityType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          entityType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEntityTypeBytes() {
      java.lang.Object ref = entityType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        entityType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = 0L;
      title_ = "";
      entityType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEntityType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEntityTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEntityTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.services.social.data.message.Social.SEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.SEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.SEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.SEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.SEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.SEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.SEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.SEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.SEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.social.data.message.Social.SEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.services.social.data.message.Social.SEntity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.services.social.data.message.Social.SEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.services.social.data.message.Social.internal_static_eu_trentorise_smartcampus_services_social_data_message_SEntity_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.services.social.data.message.Social.internal_static_eu_trentorise_smartcampus_services_social_data_message_SEntity_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        entityType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.services.social.data.message.Social.SEntity getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.services.social.data.message.Social.SEntity build() {
        eu.trentorise.smartcampus.services.social.data.message.Social.SEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.services.social.data.message.Social.SEntity buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.services.social.data.message.Social.SEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.services.social.data.message.Social.SEntity buildPartial() {
        eu.trentorise.smartcampus.services.social.data.message.Social.SEntity result = new eu.trentorise.smartcampus.services.social.data.message.Social.SEntity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.entityType_ = entityType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.services.social.data.message.Social.SEntity) {
          return mergeFrom((eu.trentorise.smartcampus.services.social.data.message.Social.SEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.services.social.data.message.Social.SEntity other) {
        if (other == eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasEntityType()) {
          setEntityType(other.getEntityType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasEntityType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              entityType_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string title = 2;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
      }
      
      // required string entityType = 3;
      private java.lang.Object entityType_ = "";
      public boolean hasEntityType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getEntityType() {
        java.lang.Object ref = entityType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          entityType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEntityType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        entityType_ = value;
        onChanged();
        return this;
      }
      public Builder clearEntityType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        entityType_ = getDefaultInstance().getEntityType();
        onChanged();
        return this;
      }
      void setEntityType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        entityType_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.services.social.data.message.SEntity)
    }
    
    static {
      defaultInstance = new SEntity(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.services.social.data.message.SEntity)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_services_social_data_message_NewsList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_services_social_data_message_NewsList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_services_social_data_message_News_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_services_social_data_message_News_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_services_social_data_message_SEntity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_services_social_data_message_SEntity_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014social.proto\0226eu.trentorise.smartcampu" +
      "s.services.social.data.message\"h\n\010NewsLi" +
      "st\022J\n\004news\030\001 \003(\0132<.eu.trentorise.smartca" +
      "mpus.services.social.data.message.News\022\020" +
      "\n\010socialId\030\002 \002(\003\"\374\001\n\004News\022\n\n\002id\030\001 \002(\003\022\031\n" +
      "\021creationTimestamp\030\002 \002(\003\022\020\n\010entityId\030\003 \002" +
      "(\003\022\022\n\nentityType\030\004 \002(\t\022\017\n\007topicId\030\005 \002(\003\022" +
      "\021\n\ttopicName\030\006 \002(\t\022\016\n\006update\030\007 \002(\010\022\r\n\005ti" +
      "tle\030\010 \001(\t\022\022\n\nproviderId\030\t \001(\003\022P\n\007related" +
      "\030\n \001(\0132?.eu.trentorise.smartcampus.servi",
      "ces.social.data.message.SEntity\"8\n\007SEnti" +
      "ty\022\n\n\002id\030\001 \002(\003\022\r\n\005title\030\002 \001(\t\022\022\n\nentityT" +
      "ype\030\003 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eu_trentorise_smartcampus_services_social_data_message_NewsList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eu_trentorise_smartcampus_services_social_data_message_NewsList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_services_social_data_message_NewsList_descriptor,
              new java.lang.String[] { "News", "SocialId", },
              eu.trentorise.smartcampus.services.social.data.message.Social.NewsList.class,
              eu.trentorise.smartcampus.services.social.data.message.Social.NewsList.Builder.class);
          internal_static_eu_trentorise_smartcampus_services_social_data_message_News_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_eu_trentorise_smartcampus_services_social_data_message_News_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_services_social_data_message_News_descriptor,
              new java.lang.String[] { "Id", "CreationTimestamp", "EntityId", "EntityType", "TopicId", "TopicName", "Update", "Title", "ProviderId", "Related", },
              eu.trentorise.smartcampus.services.social.data.message.Social.News.class,
              eu.trentorise.smartcampus.services.social.data.message.Social.News.Builder.class);
          internal_static_eu_trentorise_smartcampus_services_social_data_message_SEntity_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_eu_trentorise_smartcampus_services_social_data_message_SEntity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_services_social_data_message_SEntity_descriptor,
              new java.lang.String[] { "Id", "Title", "EntityType", },
              eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.class,
              eu.trentorise.smartcampus.services.social.data.message.Social.SEntity.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
